project:
  type: website
  output-dir: docs
  
website: 
  title: "Survival Analysis SURF 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: SURF
      - href: onelayernn.qmd
        text: try
format: 
  html: 
    theme: cosmo
    toc: true
