library(reticulate)
py_install('pandas')
py_install('matplotlib')
py_install('numpy')
reticulate::repl_python()
virtualenv_install('matplotlib')
os <- import("os")
os$listdir(".")
use_python("/xue/local/bin/python")
