library(reticulate)
py_install('pandas')
py_install('matplotlib')
py_install('numpy')
py_install('jupyter')
py_install('scikit-learn')
py_install('warnings')
reticulate::repl_python()
#virtualenv_install('matplotlib')
#os <- import("os")
#os$listdir(".")
#use_python("/opt/homebrew/bin/python3")
py_install('sksurv')
py_install('scikit-survival')
